# Generated by Django 5.1.6 on 2025-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_ticket_answered_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
