# Generated by Django 5.1.6 on 2025-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_ticket_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
